esphome:
  name: temp-example
  friendly_name: temp-example

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***********************************"

# Enable OTA updates
ota:
  password: "***********************"

# Configure WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Configure fallback hotspot (enabled if WiFi connection fails)
  ap:
    ssid: "temp-example Fallback Hotspot"
    password: "*********"

# Enable captive portal
captive_portal:

# Configure Dallas temperature sensor
dallas:
  - pin: GPIO0
    update_interval: 20s
  
sensor:
  - platform: dallas
    address: **************
    accuracy_decimals: 3
    name: "DS18B20 Temperature"
